POST http://localhost:3000/add
Content-Type: application/json

{
    "id": 2,
    "name": "Mohammad",
    "isAdmin": 1
}

###

POST http://localhost:3000/addMongo
Content-Type: application/json

{
    "title": "Transaction 2",
    "content": "18 STX",
    "author": "Thomas Lefebvre"
}

###

GET http://localhost:3000/getMongo